### ISSUE TITLE
Community Suggestion: Link to a video

### ISSUE THREAD

**Issue by Chew** [Chewbotcca/Discord-Legacy#1]
Heya! Maybe add a command to link to this ;3 https://www.youtube.com/watch?v=ndsaoMFz9J4
- MisterMasterOfMystery#7780

**Comment by Chewsterchew** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [%^trbmb](https://trello.com/c/PhHzR9mM/1-trbmb)

**Comment by Chew** [comment]
eh

**Comment by Chew** [comment]
Finally actually watched the video. has swearing. not on my christian bot.
